### ISSUE TITLE
TypeError: unhashable type: 'slice'

### ISSUE THREAD

**Issue by mymggithub** [nishantcoder97/insta-autorepost#4]
Hello,
I been getting this error
`Traceback (most recent call last):[00:00<?, ?it/s]
  File "main.py", line 58, in <module>
    scraper(profile, start, posts, username, passwd)
  File "main.py", line 17, in scraper
    pics = json_data[start - 1 : start + posts - 1]
TypeError: unhashable type: 'slice'
`
I saw that the repository is a kind of old since the changes of Instagram and I am wondering if it has to do with there changes. I am unsure

**Comment by fmchan** [comment]
i got the same error

**Comment by calvinti12** [comment]
me to any fix
